ncm:
   image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/nrt/nifi:1.0.1
   command: bash /usr/local/nifi-1.0.0/bin/run.sh ncm
   ports:
     - 9080:8080
   environment:
     NIFI_UI_BANNER_TEXT: 'Processing Cluster'
     NIFI_INSTANCE_ROLE: 'cluster-manager'
worker:
   image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/nrt/nifi:1.0.1
   command: bash /usr/local/nifi-1.0.0/bin/run.sh ncm
   environment:
     NIFI_UI_BANNER_TEXT: 'Processing Node'
     NIFI_INSTANCE_ROLE: 'cluster-node'
   ports:
     - 10000
     - 10001
     - 10002
     - 10003
     - 10004
