ncm:
   image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/nrt/nifi:1.0.1
   command: bash /usr/local/nifi-1.0.0/bin/run.sh ncm
   ports:
     - 9080:8080
   environment:
    - NIFI_UI_BANNER_TEXT=Cluster-Manager
    - NIFI_INSTANCE_ROLE=cluster-manager
    - ZK_SERVICE=${zk_link}
   external_links:
    - ${zk_link}
   labels: 
    io.rancher.container.dns: true
   restart: always
   volumes:
    - /usr/local/aeris_lib/:/usr/local/aeris_lib
worker:
   image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/nrt/nifi:1.0.1
   command: bash /usr/local/nifi-1.0.0/bin/run.sh ncm
   ports:
    - 9081:8081
   environment:
    - NIFI_UI_BANNER_TEXT=Cluster-Node
    - NIFI_INSTANCE_ROLE=cluster-node
    - ZK_SERVICE=${zk_link}
   external_links:
    - ${zk_link}
   labels: 
    io.rancher.container.dns: true
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
   restart: always
   volumes:
    - /usr/local/aeris_lib/:/usr/local/aeris_lib
   ports:
     - 10000
     - 10001
     - 10002
     - 10003
     - 10004
