.catalog:
  name: Nifi Cluster
  version: Nifi-1.0.0-rancher1
  description: |
    Apache Nifi cluster.
  minimum_rancher_version: v0.56.0
  maintainer: "Pawan Kumar <monu.pawan@gmail.com>"
  uuid: zk-0
  questions:
    - variable: "ncm_scale"
      description: "Number of Cluster Manager nodes"
      label: "ncm Nodes:"
      required: true
      default: 1
      type: "int"
    - variable: "worker_scale"
      description: "Number of worker nodes"
      label: "worker Nodes:"
      required: true
      default: 1
    - variable: "zk_link"
      description: |
        Choose the Zookeeper service to use. 
        It's really recommended a dedicated zookeeper service just for Nifi.
      label: "Zookeeper stack/service"
      default: "zookeeper/zk"
      required: true
      type: "service"
ncm:
 scale: ${ncm_scale}
worker:
 scale: ${worker_scale}
